[assyrian-royal-inscriptions]
archives = [
  "riao-ria1",
  "riao-ria2",
  "riao-ria3",
  "riao-ria4",
  "riao-ria5",
  "rinap-rinap1",
  "rinap-rinap2",
  "rinap-rinap3",
  "rinap-rinap4",
  "rinap-rinap5",
  "rinap-rinap5p1",
]
tei = ["riao-teiCorpus"]

[obabat-atletters]
archives = ["obabat-atletters"]
tei = []
